# Generated by Django 3.0.2 on 2020-01-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(verbose_name='reply creation date'),
        ),
    ]
