# Generated by Django 3.0.2 on 2020-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200118_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(verbose_name='thread creation date'),
        ),
    ]
