# Generated by Django 3.0.2 on 2020-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200118_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.CharField(max_length=190, verbose_name='author email'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='theme',
            field=models.CharField(max_length=190, verbose_name='thread theme'),
        ),
    ]
