# Generated by Django 3.0.2 on 2020-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200118_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='author email'),
        ),
    ]
